// ЗГЕНЕРОВАНО `deno task client:assets` з client/_locales/*.json — не редагувати.
//
// Рядки фреймворку вбудовані, а не вивантажуються по HTTP: у встановленому
// застосунку копіювати їх нізвідки (див. tools/generate-client-assets.ts).
// Застосунок свої рядки далі вантажить із /locales/app/<locale>.json.

export const CLIENT_LOCALES: Record<string, Record<string, string>> = {
  "en": {"common.save":"Save","common.saveAndClose":"Save and close","common.close":"Close","common.cancel":"Cancel","common.delete":"Delete","common.confirmDelete":"Delete record","common.create":"Create","common.refresh":"Refresh","common.code":"Code","common.name":"Name","common.noData":"No data","common.notFound":"Nothing found","common.recordNotFound":"Record not found or deleted","common.select":"Select","common.active":"Active","common.pick":"Pick","common.print":"Print","common.exportExcel":"Excel","common.exportTruncated":"Exported the first {count} rows","common.yes":"Yes","common.loading":"Loading...","common.open":"Open","common.search":"Search","common.records":"records","common.noOpenTabs":"No open tabs","blob.attachments":"Attachments","blob.add":"Add file","blob.choose":"Choose file","blob.replace":"Replace","blob.clear":"Clear","blob.download":"Download","blob.noImage":"No image","blob.saveFirst":"Save the record to add attachments","blob.tooLarge":"File is larger than {size}","groups.title":"Groups","groups.root":"Root","groups.add":"Add group","groups.rename":"Rename group","groups.move":"Move group","groups.delete":"Delete group","groups.name":"Group name","groups.toGroup":"To group…","groups.moveTitle":"Move to group","tabular.add":"Add row","tabular.copy":"Copy row","tabular.delete":"Delete row","tabular.up":"Up","tabular.down":"Down","tabular.total":"Total"},
  "uk": {"common.save":"Зберегти","common.saveAndClose":"Зберегти й закрити","common.close":"Закрити","common.cancel":"Скасувати","common.delete":"Видалити","common.confirmDelete":"Видалити запис","common.create":"Створити","common.open":"Відкрити","common.refresh":"Оновити","common.search":"Пошук","common.records":"записів","common.code":"Код","common.name":"Назва","common.noData":"Немає даних","common.notFound":"Нічого не знайдено","common.recordNotFound":"Запис не знайдено або видалено","common.select":"Вибрати","common.active":"Активний","common.pick":"Підбір","common.print":"Друк","common.exportExcel":"Excel","common.exportTruncated":"Вивантажено перші {count} рядків","common.yes":"Так","common.loading":"Завантаження...","common.noOpenTabs":"Немає відкритих вкладок","blob.attachments":"Вкладення","blob.add":"Додати файл","blob.choose":"Обрати файл","blob.replace":"Замінити","blob.clear":"Очистити","blob.download":"Завантажити","blob.noImage":"Немає зображення","blob.saveFirst":"Збережіть запис, щоб додати вкладення","blob.tooLarge":"Файл більший за {size}","groups.title":"Групи","groups.root":"Корінь","groups.add":"Додати групу","groups.rename":"Перейменувати групу","groups.move":"Перемістити групу","groups.delete":"Видалити групу","groups.name":"Назва групи","groups.toGroup":"До групи…","groups.moveTitle":"Перемістити до групи","tabular.add":"Додати рядок","tabular.copy":"Копіювати рядок","tabular.delete":"Видалити рядок","tabular.up":"Вище","tabular.down":"Нижче","tabular.total":"Разом"},
};
