create table if not exists app.invoice (
  id              bigint generated by default as identity primary key,
  number          varchar(20) not null,
  invoice_date    date,
  counterparty_id bigint references app.counterparty (id),
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index if not exists ix_invoice_number      on app.invoice (number);
create index if not exists ix_invoice_counterparty on app.invoice (counterparty_id);

create table if not exists app.invoice_line (
  id         bigint generated by default as identity primary key,
  invoice_id bigint not null references app.invoice (id) on delete cascade,
  line_no    int    not null default 0,
  bank_id    bigint references app.bank (id),
  qty        numeric(18,3) not null default 0,
  price      numeric(18,2) not null default 0
);

create index if not exists ix_invoice_line_invoice on app.invoice_line (invoice_id);
