-- Документ «Накладна». Власної identity немає: первинний ключ — document_id,
-- що посилається на шапку app.document. Ідентифікатор документа один на всю
-- систему, тому посилання на нього — звичайний bigint.

create table if not exists app.invoice (
  document_id     bigint primary key references app.document (id) on delete cascade,
  counterparty_id bigint not null references app.counterparty (id)
);

create index if not exists ix_invoice_counterparty on app.invoice (counterparty_id);

create table if not exists app.invoice_line (
  id          bigint generated by default as identity primary key,
  document_id bigint not null references app.invoice (document_id) on delete cascade,
  line_no     int    not null default 0,
  bank_id     bigint references app.bank (id),
  qty         numeric(18,3) not null default 0,
  price       numeric(18,2) not null default 0
);

create index if not exists ix_invoice_line_document on app.invoice_line (document_id);
