-- Валюти. Код за ISO 4217 (літерний) — він же ключ у побутовому вжитку;
-- цифровий код лишаємо для звітності та обміну з банком.

create table if not exists app.currency (
  id           bigint generated by default as identity primary key,
  code         varchar(3)  not null,
  name         varchar(100) not null,
  numeric_code varchar(3),
  symbol       varchar(8),
  is_active    boolean not null default true,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create unique index if not exists uq_currency_code on app.currency (code);
create index        if not exists ix_currency_name on app.currency (name);
