-- Зауваження до рішення — канал від людини, яка перевіряє, до того, хто робить.
--
-- Таблиця в ядрі, а не в застосунку, з двох причин. Контекст зауваження
-- (маршрут вкладки, id запису, версії) складає оболонка, тобто код фреймворку;
-- і задача повторюється в кожному рішенні, яке хтось коли-небудь перевірятиме.
-- У продуктиві та сама таблиця стає каналом «клієнт → постачальник рішення».
--
-- Екран лишається застосунку (`app/admin/remark/`) — той самий поділ, що в меню,
-- нумераторах і шаблонах друку: ядро дає механізм, склад і вигляд називає
-- застосунок.
--
-- Номера в зауваження немає: ним служить `id`. Нумератор дав би гарніший
-- («000041»), але рядок нумератора сіється з манифестів ЗАСТОСУНКУ, а модель
-- ядра манифеста не має — довелося б вимагати його від кожного рішення заради
-- косметики.
create table if not exists app.remark (
  id         bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  created_by bigint references app.users (id) on delete set null,
  updated_at timestamptz not null default now(),

  ---------------------------------------------------------------- людина
  -- `order` (замовлення) — четвертий тип, і живе він за іншим правилом:
  -- дефект виправляють, бо задум уже погоджений, а замовлення — нова робота,
  -- обсяг і строк якої називає власник рішення. Тому агент сам у роботу його
  -- не бере; тримає це `remark_answer`, а не домовленість.
  kind  varchar(20)  not null default 'error',
  title varchar(200) not null,
  body  text         not null default '',

  ---------------------------------------------------------------- машина
  -- Маршрут вкладки в тому вигляді, у якому його серіалізує клієнт
  -- (`document/invoice/edit/412`): з нього виконавець відкриває ТОЙ САМИЙ
  -- запис. Заради цього перевіряльник і виконавець і мусять дивитися в одну
  -- базу — посилання на запис 412 у чужій базі не означає нічого.
  ctx_route      varchar(200),
  ctx_model      varchar(100),
  ctx_record_id  varchar(50),
  -- Без зовнішнього ключа навмисно: довідник організацій належить застосунку,
  -- а рішення без організацій — теж рішення. Ядро тут зберігає число, не посилання.
  ctx_org_id     bigint,
  ctx_solution   varchar(200),
  ctx_framework  varchar(200),
  ctx_user_agent varchar(400),

  ---------------------------------------------------------------- виконавець
  status        varchar(20) not null default 'new',
  area          varchar(20),
  answer        text,
  answered_at   timestamptz,
  fixed_version varchar(100),
  -- Ім'я файлу в каналі зворотного зв'язку про фреймворк
  -- (`gaps/2026-08-14-…md`). Рядком, а не посиланням: той каталог лежить поза
  -- будь-якою базою.
  feedback_ref  varchar(200),
  duplicate_of  bigint references app.remark (id) on delete set null,

  ---------------------------------------------------------------- закриття
  -- Закритість — це НЕПОРОЖНІЙ `verified_at`, а не значення `status`. Стан,
  -- який виводиться, не можна ані забути проставити, ані збрехати про нього;
  -- оголошений — можна. Той самий хід, що в ознаці підтримки рішення.
  verified_at timestamptz,
  verified_by bigint references app.users (id) on delete set null,

  is_deleted boolean not null default false,

  constraint ck_remark_kind   check (kind in ('error', 'question', 'wish', 'order')),
  constraint ck_remark_status check (status in ('new', 'in_work', 'answered', 'fixed', 'rejected')),
  constraint ck_remark_area   check (area is null or area in ('solution', 'framework')),
  constraint ck_remark_title  check (length(btrim(title)) > 0)
);

-- Два запити, які виконуються найчастіше: журнал за станом і лічильник
-- неопрацьованих відповідей біля кнопки в шапці.
create index if not exists ix_remark_status
  on app.remark (status) where not is_deleted;

create index if not exists ix_remark_answered
  on app.remark (created_by) where answer is not null and verified_at is null and not is_deleted;
