-- Вкладення (бінарний об'єкт): зображення, прикріплений файл тощо.
-- Одна таблиця на весь застосунок: вкладення бувають і в документів, і в
-- довідників, тому власник описується парою (owner_model, owner_id), а не
-- окремою таблицею на кожну модель.
--
-- Зовнішнє сховище не використовується — байти лежать у bytea. Поле
-- blob_name (ім'я набору в зовнішньому сховищі) свідомо відсутнє: якщо колись
-- знадобиться S3/Azure, воно додається міграцією, а attachment_load починає
-- повертати його замість stream.
create table if not exists app.attachment (
  id          bigint generated by default as identity primary key,
  -- Ключ доступу. Сам по собі не є токеном: рантайм (server/modules/blob)
  -- підписує ним токен разом із сесією та користувачем. Ротація ключа
  -- (update … set access_key = gen_random_uuid()) миттєво знецінює всі
  -- раніше видані токени цього вкладення.
  access_key  uuid         not null default gen_random_uuid(),
  name        varchar(255) not null,
  mime        varchar(255) not null default 'application/octet-stream',
  size        bigint       not null default 0,
  sha256      varchar(64),
  stream      bytea,
  -- Власник вкладення: ключ моделі (invoice, counterparty…) та id запису.
  -- Порожній власник — «сирота»: файл завантажили, але форму не зберегли.
  -- Такі рядки прибирає app.attachment_gc.
  owner_model varchar(80),
  owner_id    bigint,
  created_by  bigint references app.users(id),
  created_at  timestamptz  not null default now()
);

create index if not exists ix_attachment_owner  on app.attachment (owner_model, owner_id);
create index if not exists ix_attachment_sha256 on app.attachment (sha256);
create index if not exists ix_attachment_orphan on app.attachment (created_at)
  where owner_model is null;
