-- Меню: склад навігації, і тільки він.
--
-- Структура й функції — у ядрі: оболонка без навігації не працює, а
-- app.user_group_menu посилається на app.user_group з пакета access. Сам СКЛАД
-- пунктів — ні: маршрути належать конкретному застосунку, тож сід лишається в
-- нього (app/admin/menu/db/data.sql), як і екрани редагування меню.
--
-- Прав тут немає жодного поля — вони живуть у app.user_group_permission і
-- лишаються єдиним джерелом. Пункт показується, коли він є в меню групи
-- І користувач має право `view` на модель його маршруту (див. app.menu_current).
-- Два джерела правди про доступ розійшлися б, і розійшлися б тихо.
--
-- Рівень «інтерфейс» (група → інтерфейс → меню) знято свідомо: він не додавав
-- жодного випадку, невиразного без нього — «дати групі меню A і B» однаково
-- описується і двома інтерфейсами, і одним інтерфейсом із двома меню, і прямим
-- зв'язком групи з меню. Лишився прямий зв'язок.

create schema if not exists app;

-- ── Одноразове прибирання прототипу ────────────────────────────────────────
-- Таблиці меню/інтерфейсів існували в базі від попереднього прототипу, але їх
-- не створював жоден підключений скрипт (моделі не було в sql.json), тож
-- форма їх непередбачувана — під маркер годиться лише щось із НОВОЇ схеми.
-- app.user_group_menu не існує рівно до першої публікації цього файлу, тому
-- умова істинна один-єдиний раз. Без неї кожна публікація зносила б
-- відредаговане адміністратором меню.
do $$
begin
  if to_regclass('app.user_group_menu') is null then
    drop table if exists app.menu_item cascade;
    drop table if exists app.menu cascade;
  end if;
end $$;

-- Інтерфейси більше не створюються ніде, тож знімаються безумовно.
-- app.user_interface / app.user_group_interface зносить ядро (@core/access).
drop table if exists app.interface_menu cascade;
drop table if exists app.interface cascade;

-- ── Меню ───────────────────────────────────────────────────────────────────
-- Іменований набір пунктів. Це і є одиниця, яку адміністратор редагує та
-- перевикористовує між групами: меню з назвою «Інтерфейс бухгалтера» — рівно
-- те саме, чим був би окремий запис у таблиці інтерфейсів.
create table if not exists app.menu (
  id         bigint generated by default as identity primary key,
  code       varchar(100) not null unique,
  name       varchar(255) not null,
  is_active  boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ix_menu_is_active on app.menu (is_active);

create table if not exists app.menu_item (
  id         bigint generated by default as identity primary key,
  menu_id    bigint not null references app.menu (id) on delete cascade,
  parent_id  bigint,
  -- Ключ злиття, а не просто мнемоніка. Пункти з різних меню вважаються одним
  -- і тим самим, коли збігається ланцюжок code від кореня: тека «Довідники» з
  -- двох меню зіллється в одну, якщо в обох у неї code = 'catalog'.
  code       varchar(100) not null,
  name       varchar(255) not null,
  icon_key   varchar(100),
  -- Маршрут в'ю (`family/model/view`), як у tab.open. null → тека.
  route_path varchar(500),
  sort_order int not null default 0,
  is_active  boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint uq_menu_item_menu_id_id unique (menu_id, id),
  -- Складений FK гарантує, що батько — з того самого меню. Без нього дерево
  -- може перетнути межу меню, і це не видно ні звідки.
  constraint fk_menu_item_parent
    foreign key (menu_id, parent_id) references app.menu_item (menu_id, id) on delete cascade,
  constraint ck_menu_item_not_self_parent check (parent_id is null or parent_id <> id)
);

-- nulls not distinct (PG 15+) — інакше унікальність не діяла б на коренях,
-- де parent_id is null, а це саме той рівень, де дублікати найпомітніші.
create unique index if not exists uq_menu_item_code
  on app.menu_item (menu_id, parent_id, code) nulls not distinct;

create index if not exists ix_menu_item_tree
  on app.menu_item (menu_id, parent_id, sort_order, id) where is_active;

-- ── Призначення групі ──────────────────────────────────────────────────────
-- Кілька меню на групу і кілька груп на користувача — злиття при завантаженні
-- неминуче в будь-якому разі, тож M:N нічого не ускладнює.
--
-- Зв'язок лежить тут, а не колонкою в app.user_group, свідомо: колонка змусила б
-- пакет access посилатися на app.menu, тобто залежати від підсистеми меню.
-- Так залежність односпрямована — menu знає про access, access про menu ні,
-- і застосунок може підключити access без меню.
create table if not exists app.user_group_menu (
  id            bigint generated by default as identity primary key,
  user_group_id bigint not null references app.user_group (id) on delete cascade,
  menu_id       bigint not null references app.menu (id) on delete cascade,
  sort_order    int not null default 0,
  is_active     boolean not null default true,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create unique index if not exists uq_user_group_menu
  on app.user_group_menu (user_group_id, menu_id);

create index if not exists ix_user_group_menu_menu
  on app.user_group_menu (menu_id) where is_active;
