-- ═══════════════════════════════════════════════════════════════════════════
-- Ядро документообігу та бухгалтерського регістру.
--
-- Ключове рішення: app.document — це ШАПКА, яка володіє ідентифікатором.
-- Таблиця конкретного документа (app.invoice тощо) не має власної identity,
-- її первинний ключ — document_id, що посилається на app.document. Звідси:
--   • журнал документів = один запит до однієї таблиці, без UNION по типах;
--   • посилання на документ = звичайний bigint, а не пара (тип, id);
--   • проведення, нумерація, позначка на видалення живуть у ядрі один раз.
--
-- У шапці лише РЕАЛЬНО спільні реквізити. Контрагента, валюти, складу тут
-- немає — вони спільні не для всіх документів. Для журналу натомість є
-- денормалізовані total і presentation, які документ заповнює при записі.
--
-- Підсумків (залишків, оборотів) система не зберігає СВІДОМО: звіти рахують
-- регістр повним скануванням за індексами нижче. Тому немає ні перерахунку
-- при скасуванні проведення, ні розсинхрону підсумків із проводками.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── Типи документів ─────────────────────────────────────────────────────────
-- Рядки генеруються з manifest.json моделей-документів при sql:assemble
-- (див. _generated/document-types.data.sql), руками не наповнюються.

create table if not exists app.document_type (
  id         bigint generated by default as identity primary key,
  code       varchar(50)  not null unique,   -- = ключ моделі з manifest.json
  name       varchar(255) not null,
  short_name varchar(50),                    -- колонка «Вид» у журналі та звітах
  prefix     varchar(3),                     -- префікс автонумерації
  sort_order int not null default 0
);

-- ── Шапка документа ─────────────────────────────────────────────────────────

create table if not exists app.document (
  id               bigint generated by default as identity primary key,
  document_type_id bigint not null references app.document_type (id),
  organization_id  bigint not null references app.organization (id),
  number           varchar(20) not null,
  -- Момент, а не дата: два документи одного дня мають детермінований порядок
  -- проведення, інакше сальдо, що наростає, стрибає між запусками звіту.
  doc_date         timestamp   not null,
  -- Денормалізація заради журналу документів і списків посилань.
  -- Заповнює документ при записі; джерело правди — його власні реквізити.
  total            numeric(18,2) not null default 0,
  presentation     text          not null default '',
  description      text,
  is_posted        boolean not null default false,
  posted_at        timestamptz,
  posted_by        bigint references app.users (id),
  is_deleted       boolean not null default false,
  created_at       timestamptz not null default now(),
  created_by       bigint references app.users (id),
  updated_at       timestamptz not null default now(),
  updated_by       bigint references app.users (id)
);

create unique index if not exists uq_document_number
  on app.document (document_type_id, organization_id, number);

-- Журнал документів і відбір за періодом.
create index if not exists ix_document_org_date
  on app.document (organization_id, doc_date) where not is_deleted;
create index if not exists ix_document_type_date
  on app.document (document_type_id, doc_date desc) where not is_deleted;

-- Основний вхід звітів: проведені документи організації за період.
create index if not exists ix_document_posted
  on app.document (organization_id, doc_date) where is_posted and not is_deleted;

create index if not exists ix_document_number on app.document (number);

-- ── Види аналітики (субконто) ───────────────────────────────────────────────
-- Реєстр вимірів: що це за субконто і звідки SQL бере знімок представлення.
-- Маршрут форми тут НЕ зберігається — клієнт резолвить його з view-manifest
-- за model_key, щоб не дублювати той самий довідник у двох місцях.

create table if not exists app.analytic_dimension (
  code         varchar(100) primary key,
  name         varchar(255) not null,
  entity_kind  varchar(20)  not null check (entity_kind in ('catalog', 'document')),
  model_key    varchar(100) not null,        -- ключ моделі для view-manifest
  target_table varchar(255) not null,        -- звідки знімати code/name
  id_column    varchar(100) not null default 'id',
  code_column  varchar(100),
  name_column  varchar(100),
  is_active    boolean not null default true
);

-- ── Налаштування аналітики рахунку ──────────────────────────────────────────
-- Які субконто і в яких слотах веде рахунок. Слотів три — як у типовому
-- українському плані рахунків.

create table if not exists app.chart_of_account_analytic (
  id             bigint generated by default as identity primary key,
  account_code   varchar(10)  not null references app.chart_of_account (code) on delete cascade,
  slot_no        int          not null check (slot_no between 1 and 3),
  dimension_code varchar(100) not null references app.analytic_dimension (code),
  is_required    boolean not null default true,
  constraint uq_chart_of_account_analytic_slot unique (account_code, slot_no)
);

create index if not exists ix_chart_of_account_analytic_account
  on app.chart_of_account_analytic (account_code);

-- ── Проводки ────────────────────────────────────────────────────────────────
-- Кореспондентська модель: дебет і кредит в одному рядку.
--
-- amount — завжди у валюті обліку (гривні): саме по ній рахуються сальдо й
-- обороти. Валютна сума (currency_amount у валюті currency_id) і кількість —
-- додаткові виміри проводки, що вмикаються ознаками рахунку (is_currency,
-- is_quantitative), як і субконто. Одна валютна сума й одна кількість на
-- проводку: у кореспонденції валютним/кількісним є один бік із двох.

create table if not exists app.journal_entry (
  id              bigint generated by default as identity primary key,
  document_id     bigint not null references app.document (id) on delete cascade,
  line_no         int    not null,
  debit_account   varchar(10) not null references app.chart_of_account (code),
  credit_account  varchar(10) not null references app.chart_of_account (code),
  amount          numeric(18,2) not null,
  currency_id     bigint references app.currency (id),  -- валюта проводки
  currency_amount numeric(18,2),                         -- сума у валюті
  quantity        numeric(18,3),                         -- кількісний облік
  description     text,
  constraint uq_journal_entry_line unique (document_id, line_no)
);

-- Вхід звітів «картка рахунку» / «оборотно-сальдова»: відбір за рахунком,
-- потім join до шапки за document_id. include(amount) робить обхід index-only.
create index if not exists ix_journal_entry_debit
  on app.journal_entry (debit_account, document_id) include (amount);
create index if not exists ix_journal_entry_credit
  on app.journal_entry (credit_account, document_id) include (amount);
create index if not exists ix_journal_entry_document
  on app.journal_entry (document_id);

-- ── Значення аналітики проводки ─────────────────────────────────────────────
-- Знімки коду й назви — щоб перейменування в довіднику не переписувало
-- історію у звітах. value_id лишається живим посиланням для drill-down.

create table if not exists app.journal_entry_analytic (
  journal_entry_id   bigint not null references app.journal_entry (id) on delete cascade,
  side               varchar(10)  not null check (side in ('debit', 'credit')),
  slot_no            int          not null check (slot_no between 1 and 3),
  dimension_code     varchar(100) not null references app.analytic_dimension (code),
  value_id           bigint       not null,
  value_code         varchar(100),
  value_name         varchar(500),
  value_presentation text         not null,
  constraint pk_journal_entry_analytic primary key (journal_entry_id, side, slot_no)
);

-- Відбір звіту за конкретним субконто («обороти по контрагенту»).
create index if not exists ix_journal_entry_analytic_value
  on app.journal_entry_analytic (dimension_code, value_id);
