-- Таблиця демо-довідника. CRUD до неї не пишеться руками — його генерує
-- `deno task sql:gen catalog/counterparty` зі схеми TypeBox, у
-- db/_generated/counterparty.crud.gen.sql. Доробки поверх генерації — у
-- db/counterparty.custom.sql.

create table if not exists app.counterparty (
  id         bigint generated by default as identity primary key,
  code       varchar(20)  not null,
  name       varchar(200) not null,
  edrpou     varchar(10),
  is_active  boolean      not null default true,
  created_at timestamptz  not null default now(),
  updated_at timestamptz  not null default now()
);

-- Ім'я унікального обмеження має значення: рантайм виводить із нього поле
-- форми (uq_counterparty_code → code) і підсвічує саме його.
create unique index if not exists uq_counterparty_code on app.counterparty (code);
create index if not exists ix_counterparty_name      on app.counterparty (name);
create index if not exists ix_counterparty_edrpou    on app.counterparty (edrpou);
create index if not exists ix_counterparty_is_active on app.counterparty (is_active);
