-- План рахунків України (спрощений типовий), перенесений із прототипу.
-- Ознаки is_analytics1..3 з прототипу тут не потрібні: які субконто веде
-- рахунок, однозначно задає app.chart_of_account_analytic нижче.

insert into app.chart_of_account (
  code, name, account_type, is_group, parent_code, is_currency
)
values
  ('10',  'Основні засоби',                               'active', true,  null, false),
  ('100', 'Інвестиційна нерухомість',                     'active', false, '10', false),
  ('101', 'Земельні ділянки',                             'active', false, '10', false),
  ('103', 'Будинки та споруди',                           'active', false, '10', false),
  ('104', 'Машини та обладнання',                         'active', false, '10', false),
  ('105', 'Транспортні засоби',                           'active', false, '10', false),
  ('106', 'Інструменти, прилади та інвентар',             'active', false, '10', false),
  ('109', 'Інші основні засоби',                          'active', false, '10', false),
  ('13',  'Знос (амортизація) необоротних активів',       'passive', true, null, false),
  ('131', 'Знос основних засобів',                        'passive', false, '13', false),
  ('132', 'Знос інших необоротних матеріальних активів',  'passive', false, '13', false),
  ('133', 'Накопичена амортизація нематеріальних активів','passive', false, '13', false),
  ('20',  'Виробничі запаси',                             'active', true, null, false),
  ('201', 'Сировина й матеріали',                         'active', false, '20', false),
  ('203', 'Паливо',                                       'active', false, '20', false),
  ('207', 'Запасні частини',                              'active', false, '20', false),
  ('209', 'Інші матеріали',                               'active', false, '20', false),
  ('22',  'Малоцінні та швидкозношувані предмети',        'active', true, null, false),
  ('221', 'Малоцінні та швидкозношувані предмети',        'active', false, '22', false),
  ('26',  'Готова продукція',                             'active', true, null, false),
  ('261', 'Готова продукція',                             'active', false, '26', false),
  ('28',  'Товари',                                       'active', true, null, false),
  ('281', 'Товари на складі',                             'active', false, '28', false),
  ('282', 'Товари в торгівлі',                            'active', false, '28', false),
  ('285', 'Торгова націнка',                              'passive', false, '28', false),
  ('30',  'Готівка',                                      'active', true, null, true),
  ('301', 'Готівка в національній валюті',                'active', false, '30', false),
  ('302', 'Готівка в іноземній валюті',                   'active', false, '30', true),
  ('31',  'Рахунки в банках',                             'active', true, null, true),
  ('311', 'Поточні рахунки в національній валюті',        'active', false, '31', false),
  ('312', 'Поточні рахунки в іноземній валюті',           'active', false, '31', true),
  ('313', 'Інші рахунки в банку в національній валюті',   'active', false, '31', false),
  ('314', 'Інші рахунки в банку в іноземній валюті',      'active', false, '31', true),
  ('33',  'Інші кошти',                                   'active', true, null, false),
  ('331', 'Грошові документи в національній валюті',      'active', false, '33', false),
  ('332', 'Грошові документи в іноземній валюті',         'active', false, '33', true),
  ('333', 'Грошові кошти в дорозі в національній валюті', 'active', false, '33', false),
  ('36',  'Розрахунки з покупцями та замовниками',        'active', true, null, true),
  ('361', 'Розрахунки з вітчизняними покупцями',          'active', false, '36', false),
  ('362', 'Розрахунки з іноземними покупцями',            'active', false, '36', true),
  ('37',  'Розрахунки з різними дебіторами',              'active', true, null, true),
  ('371', 'Розрахунки за виданими авансами',              'active', false, '37', false),
  ('372', 'Розрахунки з підзвітними особами',             'active', false, '37', false),
  ('377', 'Розрахунки з іншими дебіторами',               'active', false, '37', false),
  ('40',  'Зареєстрований (пайовий) капітал',             'passive', true, null, false),
  ('401', 'Зареєстрований (пайовий) капітал',             'passive', false, '40', false),
  ('44',  'Нерозподілені прибутки (непокриті збитки)',    'active_passive', true, null, false),
  ('441', 'Прибуток нерозподілений',                      'passive', false, '44', false),
  ('442', 'Непокриті збитки',                             'active', false, '44', false),
  ('443', 'Прибуток, використаний у звітному періоді',    'active', false, '44', false),
  ('63',  'Розрахунки з постачальниками та підрядниками', 'passive', true, null, true),
  ('631', 'Розрахунки з вітчизняними постачальниками',    'passive', false, '63', false),
  ('632', 'Розрахунки з іноземними постачальниками',      'passive', false, '63', true),
  ('64',  'Розрахунки за податками й платежами',          'active_passive', true, null, false),
  ('641', 'Розрахунки за податками',                      'active_passive', false, '64', false),
  ('642', 'Розрахунки за обов''язковими платежами',       'active_passive', false, '64', false),
  ('643', 'Податкові зобов''язання',                      'active_passive', false, '64', false),
  ('644', 'Податковий кредит',                            'active_passive', false, '64', false),
  ('65',  'Розрахунки за страхуванням',                   'passive', true, null, false),
  ('651', 'За розрахунками із загальнообов''язкового державного соціального страхування', 'passive', false, '65', false),
  ('66',  'Розрахунки за виплатами працівникам',          'passive', true, null, false),
  ('661', 'Розрахунки за заробітною платою',              'passive', false, '66', false),
  ('663', 'Розрахунки за іншими виплатами',               'passive', false, '66', false),
  ('68',  'Розрахунки за іншими операціями',              'active_passive', true, null, true),
  ('681', 'Розрахунки за авансами одержаними',            'passive', false, '68', false),
  ('685', 'Розрахунки з іншими кредиторами',              'active_passive', false, '68', false),
  ('70',  'Доходи від реалізації',                        'passive', true, null, false),
  ('701', 'Дохід від реалізації готової продукції',       'passive', false, '70', false),
  ('702', 'Дохід від реалізації товарів',                 'passive', false, '70', false),
  ('703', 'Дохід від реалізації робіт і послуг',          'passive', false, '70', false),
  ('79',  'Фінансові результати',                         'active_passive', true, null, false),
  ('791', 'Результат операційної діяльності',             'active_passive', false, '79', false),
  ('792', 'Результат фінансових операцій',                'active_passive', false, '79', false),
  ('793', 'Результат іншої діяльності',                   'active_passive', false, '79', false),
  ('90',  'Собівартість реалізації',                      'active', true, null, false),
  ('901', 'Собівартість реалізованої готової продукції',  'active', false, '90', false),
  ('902', 'Собівартість реалізованих товарів',            'active', false, '90', false),
  ('903', 'Собівартість реалізованих робіт і послуг',     'active', false, '90', false),
  ('91',  'Загальновиробничі витрати',                    'active', true, null, false),
  ('911', 'Загальновиробничі витрати',                    'active', false, '91', false),
  ('92',  'Адміністративні витрати',                      'active', true, null, false),
  ('921', 'Адміністративні витрати',                      'active', false, '92', false),
  ('93',  'Витрати на збут',                              'active', true, null, false),
  ('931', 'Витрати на збут',                              'active', false, '93', false),
  ('94',  'Інші витрати операційної діяльності',          'active', true, null, false),
  ('941', 'Витрати на дослідження і розробки',            'active', false, '94', false),
  ('949', 'Інші витрати операційної діяльності',          'active', false, '94', false)
on conflict (code) do update
set
  name         = excluded.name,
  account_type = excluded.account_type,
  is_group     = excluded.is_group,
  parent_code  = excluded.parent_code,
  is_currency  = excluded.is_currency;

-- Кількісний облік — на товарно-матеріальних рахунках. У сідмісиві вище
-- ознака не задавалась (перенесена з прототипу без неї), тому вмикаємо тут.
update app.chart_of_account set is_quantitative = true
where code in ('201', '203', '207', '209', '22', '221', '26', '261', '281', '282');

-- Налаштування аналітики рахунків (chart_of_account_analytic) живе в
-- _sqlinit/document_core/db/data.sql — поруч із самими вимірами, бо посилається
-- на них зовнішнім ключем і має публікуватися після них.
