-- План рахунків. Ключ для проводок — code, а не id: у бухгалтерії посилаються
-- саме на номер рахунку, і він же читається у звітах без join.
-- Ієрархія теж по коду (parent_code), бо це природний ключ субрахунку.

create table if not exists app.chart_of_account (
  id              bigint generated by default as identity primary key,
  code            varchar(10)  not null unique,
  name            varchar(500) not null,
  -- active | passive | active_passive — визначає, з якого боку рахується сальдо
  account_type    varchar(20)  not null,
  parent_code     varchar(10)  references app.chart_of_account (code),
  is_group        boolean not null default false,  -- на групи проводок не буває
  is_off_balance  boolean not null default false,  -- позабалансовий
  is_currency     boolean not null default false,  -- валютний облік
  is_quantitative boolean not null default false,  -- кількісний облік
  is_active       boolean not null default true,
  sort_order      int     not null default 0,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  constraint ck_chart_of_account_type check (
    account_type in ('active', 'passive', 'active_passive')
  )
);

create index if not exists ix_chart_of_account_parent on app.chart_of_account (parent_code);
create index if not exists ix_chart_of_account_name   on app.chart_of_account (name);
