-- Ієрархічний довідник (патерн A2v10): групи — ОКРЕМА таблиця, а не рядки
-- моделі з прапорцем is_group. Список і lookup ніколи не мішають групи з
-- елементами, пагінація не потребує фільтра «без груп», FK прозорі.

create table if not exists app.nomenclature_group (
  id         bigint generated by default as identity primary key,
  parent_id  bigint references app.nomenclature_group (id),
  name       varchar(200) not null,
  created_at timestamptz  not null default now(),
  updated_at timestamptz  not null default now()
);

create index if not exists ix_nomenclature_group_parent on app.nomenclature_group (parent_id);

create table if not exists app.nomenclature (
  id         bigint generated by default as identity primary key,
  code       varchar(20)  not null,
  name       varchar(200) not null,
  unit       varchar(20),
  -- null — корінь. Видалення групи заборонено, поки в ній є елементи
  -- (перевіряє nomenclature_group_delete), тож каскад тут не потрібен.
  group_id   bigint references app.nomenclature_group (id),
  is_active  boolean      not null default true,
  created_at timestamptz  not null default now(),
  updated_at timestamptz  not null default now()
);

create unique index if not exists uq_nomenclature_code  on app.nomenclature (code);
create index if not exists ix_nomenclature_name  on app.nomenclature (name);
create index if not exists ix_nomenclature_group on app.nomenclature (group_id);
