-- Кодом банку є МФО — власний загальновживаний ідентифікатор, як ISO-код у
-- валюти. Окремої колонки code немає: вона була дублем МФО і другим полем,
-- яке довелося б заповнювати тим самим значенням.
create table if not exists app.bank (
  id         bigint generated by default as identity primary key,
  mfo        varchar(6)   not null,
  name       varchar(200) not null,
  is_deleted boolean      not null default false,
  created_at timestamptz  not null default now(),
  updated_at timestamptz  not null default now()
);

-- Унікальність МФО живе в міграції (uq_bank_mfo), а не тут: на наявній базі
-- колонка стає not null і наповнюється значеннями з code саме міграцією, і
-- створювати індекс до того було б передчасно. Порядок секцій: структура →
-- міграції → функції → сід, тож на новій базі індекс теж встигає з'явитися
-- до перших даних.
create index if not exists ix_bank_name on app.bank (name);
