-- Організація — власна юридична особа, від імені якої ведеться облік.
-- Мінімальний набір реквізитів: усе, що потрібно шапці документа та звітам.
-- Адреси, контакти, банківські рахунки додаються окремо, коли знадобляться.

create table if not exists app.organization (
  id                bigint generated by default as identity primary key,
  code              varchar(9)   not null,
  name              varchar(150) not null,
  full_name         varchar(500),
  edrpou            varchar(20),
  -- Префікс автонумерації документів цієї організації.
  prefix            varchar(3),
  legal_person_kind varchar(40)  not null default 'legal_entity',
  -- Логотип: посилання на вкладення (app.attachment). Видалення вкладення
  -- лишає поле порожнім, а не видаляє організацію.
  logo_id           bigint references app.attachment(id) on delete set null,
  is_active         boolean      not null default true,
  created_at        timestamptz  not null default now(),
  updated_at        timestamptz  not null default now(),
  constraint ck_organization_legal_person_kind check (
    legal_person_kind in ('legal_entity', 'individual_entrepreneur')
  )
);

create unique index if not exists uq_organization_code   on app.organization (code);
create index        if not exists ix_organization_name   on app.organization (name);
create index        if not exists ix_organization_edrpou on app.organization (edrpou);
