-- Незмінний журнал виконання команд моделей. Payload навмисно не зберігається:
-- у ньому можуть бути паролі, токени або інші персональні дані; для аудиту
-- достатньо виконавця, операції, запису та її результату.
create table if not exists app.audit_log (
  id          bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  user_id     bigint not null references app.users (id) on delete restrict,
  model       varchar(100) not null,
  command     varchar(100) not null,
  record_id   bigint,
  is_success  boolean not null,
  constraint ck_audit_log_model check (model ~ '^[a-z][a-z0-9_]*$'),
  constraint ck_audit_log_command check (command ~ '^[a-zA-Z][a-zA-Z0-9_]*$')
);

create index if not exists ix_audit_log_record
  on app.audit_log (model, record_id, occurred_at desc) where record_id is not null;
create index if not exists ix_audit_log_user_time
  on app.audit_log (user_id, occurred_at desc);