-- Незмінний журнал виконання команд моделей. Payload навмисно не зберігається:
-- у ньому можуть бути паролі, токени або інші персональні дані; для аудиту
-- достатньо виконавця, операції, запису та її результату.
create table if not exists app.audit_log (
  id          bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  user_id     bigint not null references app.users (id) on delete restrict,
  model       varchar(100) not null,
  command     varchar(100) not null,
  record_id   bigint,
  is_success  boolean not null,
  constraint ck_audit_log_model check (model ~ '^[a-z][a-z0-9_]*$'),
  constraint ck_audit_log_command check (command ~ '^[a-zA-Z][a-zA-Z0-9_]*$')
);

create index if not exists ix_audit_log_record
  on app.audit_log (model, record_id, occurred_at desc) where record_id is not null;
create index if not exists ix_audit_log_user_time
  on app.audit_log (user_id, occurred_at desc);

-- ── Налаштування журналу ────────────────────────────────────────────────────
-- Що саме журналювати — НАЛАШТУВАННЯ УСТАНОВКИ, а не властивість моделі. Доти
-- політика жила в `manifest.json`, тобто в рішенні: щоб адміністратор увімкнув
-- журнал на своїх довідниках, треба було правити застосунок і перевикочувати
-- його — а рішення на підтримці таку правку ще й знімає з підтримки (див.
-- solution:status). Тому правило переїхало в базу, до екрана.
--
-- Рядки сіє деплой (`_generated/audit-settings.data.sql`, збирається з
-- манифестів) через `on conflict do nothing`: перелік моделей приходить із
-- застосунку, а РІВЕНЬ після сіву належить адміністратору — той самий поділ,
-- що в нумераторах і шаблонах друку.
--
-- Умовчання — `none`: журнал вимкнений, поки його не ввімкнули свідомо. Це
-- зміна проти колишнього умовчання «писати змінювальні команди», і зроблена
-- вона навмисно: обсяг журналу тепер називає той, хто за нього відповідає.
create table if not exists app.audit_setting (
  model      varchar(100) primary key,
  -- none    — не журналювати нічого;
  -- changes — команди, що МІНЯЮТЬ запис (право create/edit/delete/post/unpost);
  -- all     — усі команди моделі, включно з читанням (list/get/lookup, друк).
  --
  -- Читання відділене від змін не за іменем команди, а за ПРАВОМ, якого вона
  -- вимагає: рантайм його й так рахує для перевірки доступу, і нестандартна
  -- команда (`copy`, `moveToGroup`, TS-команда) потрапляє в потрібний кошик
  -- сама — без другого оголошення, яке розійшлося б із першим.
  level      varchar(20) not null default 'none',
  updated_at timestamptz not null default now(),
  constraint ck_audit_setting_level check (level in ('none', 'changes', 'all'))
);