create table if not exists app.document_types (
  id bigint generated by default as identity primary key,
  code varchar(50) not null unique,
  name varchar(255) not null,
  short_name varchar(50),
  sort_order int not null default 0
);

create table if not exists app.documents (
  id bigint generated by default as identity primary key,
  document_type_id bigint not null references app.document_types(id),
  organization_id bigint not null references app.organization(id),
  number varchar(50) not null,
  date date not null,
  counterparty_id bigint references app.counterparties(id),
  currency_id bigint not null references app.currency(id),
  amount numeric(15, 2) not null default 0,
  description text,
  is_posted boolean not null default false,
  posted_at timestamptz,
  posted_by bigint references app.users(id),
  created_by bigint not null references app.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_documents_date on app.documents(date);
create index if not exists idx_documents_type on app.documents(document_type_id);
create index if not exists idx_documents_org on app.documents(organization_id);
create index if not exists idx_documents_counterparty on app.documents(counterparty_id);

create table if not exists app.analytic_dimensions (
  code varchar(100) primary key,
  name varchar(255) not null,
  entity_kind varchar(20) not null check (entity_kind in ('catalog', 'document')),
  model_key varchar(100) not null,
  default_view varchar(50) not null default 'edit',
  target_table varchar(255) not null,
  document_type_code varchar(50) references app.document_types(code),
  id_column varchar(100) not null default 'id',
  code_column varchar(100),
  name_column varchar(100),
  presentation_column varchar(100),
  is_active boolean not null default true
);

create index if not exists idx_analytic_dimensions_kind on app.analytic_dimensions(entity_kind);
create index if not exists idx_analytic_dimensions_active on app.analytic_dimensions(is_active);

create table if not exists app.chart_of_account_analytics (
  id bigint generated by default as identity primary key,
  account_code varchar(10) not null references app.chart_of_accounts(code) on delete cascade,
  slot_no int not null check (slot_no between 1 and 3),
  dimension_code varchar(100) not null references app.analytic_dimensions(code),
  is_required boolean not null default true,
  created_at timestamptz not null default now(),
  constraint uq_chart_of_account_analytics_account_slot unique (account_code, slot_no)
);

create index if not exists idx_chart_of_account_analytics_account on app.chart_of_account_analytics(account_code);
create index if not exists idx_chart_of_account_analytics_dimension on app.chart_of_account_analytics(dimension_code);

create table if not exists app.journal_entries (
  id bigint generated by default as identity primary key,
  document_id bigint not null references app.documents(id) on delete cascade,
  line_number int not null,
  debit_account varchar(10) not null references app.chart_of_accounts(code),
  credit_account varchar(10) not null references app.chart_of_accounts(code),
  amount numeric(15, 2) not null,
  currency_id bigint references app.currency(id),
  currency_amount numeric(15, 2),
  quantity numeric(15, 3),
  description text,
  debit_counterparty_id bigint references app.counterparties(id),
  credit_counterparty_id bigint references app.counterparties(id),
  created_at timestamptz not null default now(),
  constraint uq_journal_entries_document_line unique (document_id, line_number)
);

create index if not exists idx_journal_document on app.journal_entries(document_id);
create index if not exists idx_journal_debit on app.journal_entries(debit_account);
create index if not exists idx_journal_credit on app.journal_entries(credit_account);

create table if not exists app.journal_entry_analytics (
  journal_entry_id bigint not null references app.journal_entries(id) on delete cascade,
  side varchar(10) not null check (side in ('debit', 'credit')),
  slot_no int not null check (slot_no between 1 and 3),
  dimension_code varchar(100) not null references app.analytic_dimensions(code),
  value_id bigint not null,
  value_code_snapshot varchar(100),
  value_name_snapshot varchar(500),
  value_presentation_snapshot text not null,
  created_at timestamptz not null default now(),
  constraint pk_journal_entry_analytics primary key (journal_entry_id, side, slot_no)
);

create index if not exists idx_journal_entry_analytics_dimension_value
  on app.journal_entry_analytics(dimension_code, value_id);
create index if not exists idx_journal_entry_analytics_side_dimension_value
  on app.journal_entry_analytics(side, dimension_code, value_id);
