-- Приймання даних із ЗОВНІШНЬОГО джерела: сесія, сировина, карта ключів.
--
-- ЩО ЦЕ ЗА ЗАДАЧА. Дані приносить чужа програма з чужої машини — обробка в базі
-- клієнта, касове ПЗ, банк-клієнт, інша облікова система. Вона ходить лише
-- НАЗОВНІ (вхідних з'єднань не приймає), результат буває на сотні тисяч рядків,
-- з'єднання рветься, а людина закриває вікно посеред вивантаження.
--
-- ЧОМУ СИРОВИНА ЛЯГАЄ ОКРЕМО, А НЕ ПРЯМО В МОДЕЛІ. Три причини, і кожна
-- з'ясовується на другій ітерації, а не на першій:
--
--   1. конвертувати доводиться БАГАТО РАЗІВ. Поправили правило — прогнали по
--      тих самих рядках, не питаючи джерело заново. Ітерацій переносу буває
--      п'ять-десять, і кожна вимагала б нового вивантаження;
--   2. помилки стають ПОРЯДКОВИМИ, а не прогонними: один зіпсований контрагент
--      не валить перенесення, а йде в список «вимагає уваги»;
--   3. кожен рядок нашої бази простежується назад: запис → партія → пакет →
--      запит → база й реліз джерела.
--
-- ЧОГО ТУТ НЕМАЄ НАВМИСНО. Ані строку зберігання, ані автоочищення: сировину
-- зносить КОРИСТУВАЧ командою, коли вважає перенесення закінченим. Система, що
-- сама стирає те, з чого зроблено облік, позбавляє єдиного способу відповісти
-- на питання «звідки взявся цей рядок» — а питають його через півроку, а не
-- наступного дня.

-- ── Сесія ───────────────────────────────────────────────────────────────────
-- Одне перенесення: хто, звідки, з якими параметрами, і чим це скінчилося.
--
-- Сесія тримає КАНАЛ, а не дані: сировина живе партіями нижче. Її роль —
-- пустити чужий процес усередину рівно на цю роботу й на цей час.

create table if not exists app.import_session (
  id       bigint generated by default as identity primary key,
  -- Звідки: `bas`, `excel`, `altera`. Рядок вільний — ядро джерел не знає й не
  -- має знати, бо їх називає застосунок разом із набором правил.
  source   varchar(50) not null,

  -- Параметри перенесення, які ядро НЕ тлумачить: дата початку обліку,
  -- організація, чи возити документи, режим прогону. Вони належать
  -- застосунку, а ядро лише везе їх до того, хто будує план.
  params   jsonb not null default '{}'::jsonb,

  -- Що адаптер сказав про себе: GUID бази, реліз конфігурації, версія обробки.
  -- Лягає як є й не перевіряється — це свідчення сторони, а не наші дані.
  -- Порожньо, доки ніхто не спарувався.
  passport jsonb,

  -- open — канал живий; closed — закритий, токен мертвий, нові партії не
  -- приймаються. Третього стану немає навмисно: «успішно» чи ні — питання до
  -- прогону конвертації, а не до каналу.
  state    varchar(20) not null default 'open',

  -- Код спарювання — ОДНОРАЗОВІ облікові дані, тому зберігається хеш, як у
  -- сесії й у токена. Людина бачить шість знаків на екрані й вводить їх у
  -- чужій програмі; ми ж із бази його не відновимо навіть при бажанні.
  pairing_code_hash varchar(64),
  pairing_expires_at timestamptz,

  -- Токен, виданий цьому каналу (`app.access_token.scope = 'import:<id>'`).
  -- Закриття сесії його відкликає — саме тому посилання зберігається, а не
  -- вважається, що токен «десь є».
  access_token_id bigint references app.access_token (id) on delete set null,

  created_by bigint not null references app.users (id) on delete restrict,
  created_at timestamptz not null default now(),
  paired_at  timestamptz,
  closed_at  timestamptz,

  constraint ck_import_session_source check (source ~ '^[a-z][a-z0-9_.-]*$'),
  constraint ck_import_session_state  check (state in ('open', 'closed'))
);

-- Спарювання шукає за хешем коду, і лише серед живих сесій.
create unique index if not exists uq_import_session_pairing
  on app.import_session (pairing_code_hash) where pairing_code_hash is not null;
create index if not exists ix_import_session_user
  on app.import_session (created_by, created_at desc);

-- ── Партія ──────────────────────────────────────────────────────────────────
-- Результат ОДНОГО запиту до джерела: залишки рахунку з субконто, довідник,
-- зріз регістра. Приходить частинами, тому має власний стан.

create table if not exists app.source_batch (
  id         bigint generated by default as identity primary key,
  session_id bigint not null references app.import_session (id) on delete restrict,
  -- Дублює `session.source` навмисно: партія переживає видалення сировини й
  -- лишається слідом, а питання «з якого джерела це приїхало» ставлять саме до
  -- неї. Похід у сесію за одним рядком тут коштував би дорожче за колонку.
  source     varchar(50) not null,
  -- Що саме замовляли: ім'я пункту плану («Справочник.Контрагенты»,
  -- «ОстаткиПоСчету_631»). Ядро його не тлумачить — план будує застосунок.
  -- Довжину тут і в `kind`/`ref` сировини не обмежуємо: ці рядки складає
  -- ДЖЕРЕЛО, а його імена ми не контролюємо (див. migration.sql).
  query      text not null,

  -- Паспорт адаптера на момент цієї партії. Знову дубль сесійного — і знову
  -- навмисний: між першою й останньою партією базу могли оновити, а знімок
  -- мусить пам'ятати, чим його зняли.
  passport   jsonb,
  -- Версія прикладного рішення, яка приймала партію. Після оновлення стара
  -- сировина конвертується НОВИМИ правилами — зазвичай це й потрібно, але
  -- результат відрізнятиметься від минулого разу, і це має бути видно.
  solution_version varchar(100),

  -- open   — частини приймаються;
  -- ready  — прийшли всі й зійшлися суми: партію можна конвертувати;
  -- broken — не зійшлося; партія НЕ вважається прийнятою наполовину.
  state      varchar(20) not null default 'open',
  -- Скільки частин обіцяв адаптер — стає відомо лише в кінці, разом із
  -- підсумком. Доти null: «скільки буде» не знає й він сам, поки не дочитає.
  part_count  integer,
  -- Скільки рядків обіцяв. Звіряється з тим, що справді лягло.
  row_count   integer,
  error       text,

  created_at  timestamptz not null default now(),
  finished_at timestamptz,

  constraint ck_source_batch_state check (state in ('open', 'ready', 'broken'))
);

create index if not exists ix_source_batch_session
  on app.source_batch (session_id, created_at desc);

-- Частина партії: сам факт приймання. Рядки з неї лежать у таблицях нижче, а
-- тут — облік того, що прийшло й чи не зіпсувалося.
--
-- Окрема таблиця, а не лічильник у партії, рівно заради ІДЕМПОТЕНТНОСТІ:
-- з'єднання рветься посеред вивантаження, адаптер повторює частину, і повтор
-- не має подвоїти нічого. Унікальність (партія, номер) тримає це в базі, а не
-- в домовленості з адаптером.
create table if not exists app.source_part (
  batch_id    bigint not null references app.source_batch (id) on delete cascade,
  part_no     integer not null,
  -- sha256 тіла частини. Не захист від зловмисника — свідчення, що по дорозі
  -- нічого не загубилося: обрізане на середині тіло розбирається в коректний
  -- JSON рівно доти, доки не розбереться.
  sha256      varchar(64) not null,
  row_count   integer not null,
  received_at timestamptz not null default now(),
  constraint pk_source_part primary key (batch_id, part_no),
  constraint ck_source_part_no check (part_no >= 1)
);

-- ── Сировина: два види, і це не дубль ───────────────────────────────────────
-- Перша версія схеми мала одну таблицю — об'єкт із власним ключем. І в рядка
-- залишків ключа не знайшлося: це рядок результату запиту, а не об'єкт. А таких
-- рядків — половина того, що переноситься.

-- Об'єкт джерела: має власний ключ (у 1С — GUID довідника чи документа).
create table if not exists app.source_object (
  batch_id bigint not null references app.source_batch (id) on delete cascade,
  source   varchar(50) not null,
  -- Що це таке в термінах ДЖЕРЕЛА: «Справочник.Контрагенты». Наша модель тут
  -- не згадується — відповідність оголошує правило конвертації.
  kind     text not null,
  -- Ключ об'єкта в джерелі.
  ref      text not null,
  payload  jsonb not null,

  -- received  — лежить як приїхало;
  -- converted — правило відпрацювало, payload моделі зібрано;
  -- loaded    — записано в модель;
  -- deferred  — чекає на нерозв'язане посилання, піде наступним проходом;
  -- failed    — не вийшло; причина в `error`, рядок у «вимагає уваги».
  state    varchar(20) not null default 'received',
  error    text,

  constraint pk_source_object primary key (batch_id, kind, ref),
  constraint ck_source_object_state
    check (state in ('received', 'converted', 'loaded', 'deferred', 'failed'))
);

-- Ключ включає ПАРТІЮ: новий знімок — нова партія, стара не затирається.
-- Інакше простежуваність «звідки цей рядок» зникає на другій ітерації, а саме
-- других ітерацій тут і буває вісім.
create index if not exists ix_source_object_lookup
  on app.source_object (source, kind, ref);
create index if not exists ix_source_object_work
  on app.source_object (batch_id, state);

-- Рядок результату запиту: власного ключа не має. Залишки, зрізи регістрів,
-- еталон звірки.
create table if not exists app.source_row (
  batch_id bigint not null references app.source_batch (id) on delete cascade,
  query    text not null,
  line_no  integer not null,
  payload  jsonb not null,
  constraint pk_source_row primary key (batch_id, query, line_no)
);

-- ── Рішення людини й карта ключів ───────────────────────────────────────────
-- Обидві таблиці ПЕРЕЖИВАЮТЬ видалення сировини — і це головне, що про них
-- треба знати. Сировину зносять як відпрацьований матеріал; відповідь на
-- питання «якому нашому запису відповідає цей GUID» потрібна й через рік:
-- довантаження документів, повторний прогін, «звідки взявся цей контрагент».

-- Рішення: те, чого не виводиться ні з ключа, ні з правила. «Ці три GUID — один
-- контрагент», «цей GUID = наш код 00042», «не переносити».
--
-- Рішення ПЕРВИННЕ, карта похідна: карту можна стерти й відбудувати з сировини
-- та рішень, рішення — ні, це єдине тут, що створила людина.
create table if not exists app.source_decision (
  id       bigint generated by default as identity primary key,
  source   varchar(50) not null,
  kind     text not null,
  ref      text not null,
  -- Зміст рішення: на що замінити, з чим злити, чи не переносити взагалі.
  -- Форму визначає застосунок — ядро возить.
  decision jsonb not null,

  -- proposed  — запропонував агент або код; у карту НЕ потрапляє;
  -- confirmed — підтвердила людина. Тільки це застосовується.
  state    varchar(20) not null default 'proposed',
  -- Чому саме так. Для `proposed` — довід агента, для `confirmed` — підстава
  -- людини. Порожнє поле тут через півроку коштує повторного розслідування.
  reason   text,

  created_by   bigint references app.users (id) on delete set null,
  created_at   timestamptz not null default now(),
  confirmed_by bigint references app.users (id) on delete set null,
  confirmed_at timestamptz,

  constraint ck_source_decision_state check (state in ('proposed', 'confirmed'))
);

create unique index if not exists uq_source_decision
  on app.source_decision (source, kind, ref);

-- Карта: «цей ключ джерела — ось цей наш запис».
create table if not exists app.source_ref (
  source    varchar(50) not null,
  kind      text not null,
  ref       text not null,
  -- Наша модель і наш id. FK сюди поставити нема куди — моделі не таблиця, а
  -- реєстр; перевірку імені робить той, хто пише.
  entity    varchar(100) not null,
  entity_id bigint not null,
  -- exact    — зійшлося за ключем (ЄДРПОУ, ІПН, IBAN, артикул);
  -- decision — застосовано підтверджене рішення людини;
  -- new      — записано новим.
  method    varchar(20) not null,
  created_at timestamptz not null default now(),

  -- Унікальність включає `entity`: один об'єкт джерела буває ДВОМА нашими —
  -- документ із товарами й основними засобами стає двома документами. Перша
  -- версія ключа була без `entity`, і впіймалося це лише на перевірці.
  constraint pk_source_ref primary key (source, ref, entity),
  constraint ck_source_ref_entity check (entity ~ '^[a-z][a-z0-9_]*$'),
  constraint ck_source_ref_method check (method in ('exact', 'decision', 'new'))
);

-- Зворотний хід: «а цей наш запис звідки?» — питання зі стандартного набору,
-- і без індексу воно означало б скан усієї карти.
create index if not exists ix_source_ref_entity
  on app.source_ref (entity, entity_id);
