create schema if not exists app;

create table if not exists app.menu (
  id bigint generated by default as identity primary key,
  code varchar(100) not null unique,
  name varchar(255) not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists app.interface (
  id bigint generated by default as identity primary key,
  code varchar(100) not null unique,
  name varchar(255) not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists app.interface_menu (
  id bigint generated by default as identity primary key,
  interface_id bigint not null references app.interface(id) on delete cascade,
  menu_id bigint not null references app.menu(id) on delete cascade,
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_interface_menu unique (interface_id, menu_id)
);

create table if not exists app.user_group (
  id bigint generated by default as identity primary key,
  code varchar(100) not null unique,
  name varchar(255) not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists app.user_group_member (
  id bigint generated by default as identity primary key,
  user_group_id bigint not null references app.user_group(id) on delete cascade,
  user_id bigint not null references app.users(id) on delete cascade,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_user_group_member unique (user_group_id, user_id)
);

create table if not exists app.user_interface (
  id bigint generated by default as identity primary key,
  user_id bigint not null references app.users(id) on delete cascade,
  interface_id bigint not null references app.interface(id) on delete cascade,
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_user_interface unique (user_id, interface_id)
);

create table if not exists app.user_group_interface (
  id bigint generated by default as identity primary key,
  user_group_id bigint not null references app.user_group(id) on delete cascade,
  interface_id bigint not null references app.interface(id) on delete cascade,
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_user_group_interface unique (user_group_id, interface_id)
 );

create table if not exists app.menu_item (
  id bigint generated by default as identity primary key,
  menu_id bigint not null references app.menu(id) on delete cascade,
  parent_id bigint,
  code varchar(100),
  name varchar(255) not null,
  icon_key varchar(100),
  sort_order int not null default 0,
  route_path varchar(500),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_menu_item_menu_id_id unique (menu_id, id),
  constraint fk_menu_item_parent
    foreign key (menu_id, parent_id)
    references app.menu_item(menu_id, id)
    on delete cascade,
  constraint ck_menu_item_not_self_parent
    check (parent_id is null or parent_id <> id)
);

create index if not exists ix_menu_name on app.menu (name);
create index if not exists ix_menu_is_active on app.menu (is_active);

create index if not exists ix_interface_name on app.interface (name);
create index if not exists ix_interface_is_active on app.interface (is_active);

create index if not exists ix_user_group_name on app.user_group (name);
create index if not exists ix_user_group_is_active on app.user_group (is_active);

create index if not exists ix_interface_menu_interface_order
  on app.interface_menu (interface_id, sort_order, id);

create index if not exists ix_interface_menu_menu on app.interface_menu (menu_id);
create index if not exists ix_interface_menu_is_active on app.interface_menu (is_active);

create index if not exists ix_user_group_member_group on app.user_group_member (user_group_id, is_active, id);
create index if not exists ix_user_group_member_user on app.user_group_member (user_id, is_active, id);

create index if not exists ix_user_interface_user_order on app.user_interface (user_id, sort_order, id);
create index if not exists ix_user_interface_interface on app.user_interface (interface_id, is_active, id);

create index if not exists ix_user_group_interface_group_order
  on app.user_group_interface (user_group_id, sort_order, id);

create index if not exists ix_user_group_interface_interface
  on app.user_group_interface (interface_id, is_active, id);

create index if not exists ix_menu_item_menu_parent_order
  on app.menu_item (menu_id, parent_id, sort_order, id);

create index if not exists ix_menu_item_icon_key on app.menu_item (icon_key);
create index if not exists ix_menu_item_route_path on app.menu_item (route_path);
create index if not exists ix_menu_item_is_active on app.menu_item (is_active);