create extension if not exists pgcrypto;
create schema if not exists app;

create table if not exists app.users (
  id bigint generated by default as identity primary key,
  login varchar(100) not null unique,
  password_hash varchar(255) not null,
  full_name varchar(255) not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ix_users_is_active on app.users (is_active);

create table if not exists app.auth_session (
  id uuid primary key default gen_random_uuid(),
  user_id bigint not null references app.users(id) on delete cascade,
  auth_method varchar(50) not null,
  token_hash varchar(64) not null unique,
  expires_at timestamptz not null,
  last_seen_at timestamptz,
  revoked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ix_auth_session_user_id on app.auth_session (user_id);
create index if not exists ix_auth_session_active_lookup on app.auth_session (token_hash, expires_at)
  where revoked_at is null;
