-- Курси валют — періодичний регістр: ключ (валюта), дата, значення.
--
-- Унікального індексу (currency_id, period) тут НЕМАЄ навмисно: його генерує
-- `sql:gen` з блока `periodic` манифеста разом із функціями зрізу — щоб напрямок
-- (`period desc`) не розійшовся з тим, як його читає `<model>_at`.
create table if not exists app.currency_rate (
  id           bigint generated by default as identity primary key,
  currency_id  bigint not null references app.currency (id),
  period       date   not null,
  rate         numeric(18,6) not null,
  -- За скільки одиниць валюти заданий курс: 100 для дрібних валют.
  multiplicity int    not null default 1,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
