-- Зовнішній сервіс: адреса, логін і токен доступу (банк, ЕДО, служба доставки).
-- Еталон поля-секрету: колонки під токен тут НЕМАЄ — він лежить зашифрованим
-- в app.secret (пакет ядра @core/secret), і жоден get/list цієї таблиці його
-- віддати не може. Див. docs/secret.md.
create table if not exists app.external_service (
  id         bigint generated by default as identity primary key,
  name       varchar(200) not null,
  url        varchar(500),
  login      varchar(200),
  is_deleted boolean      not null default false,
  created_at timestamptz  not null default now(),
  updated_at timestamptz  not null default now()
);

create index if not exists ix_external_service_name on app.external_service (name);
