// Generated from model manifests. Do not edit manually.

export const viewManifest = [
  { route: "report/account_card/list", moduleFile: "app/report/account_card/accountCardReport.ts", titleKey: "accountCard.title" },
  { route: "admin/audit_log/list", moduleFile: "app/admin/audit_log/auditLogList.ts", titleKey: "auditLog.titleMany" },
  { route: "admin/audit_setting/list", moduleFile: "app/admin/audit_setting/auditSettingList.ts", titleKey: "auditSetting.titleMany" },
  { route: "admin/audit_setting/edit", moduleFile: "app/admin/audit_setting/auditSettingEdit.ts", titleKey: "auditSetting.titleOne" },
  { route: "catalog/bank/list", moduleFile: "app/catalog/bank/bankList.ts", titleKey: "bank.titleMany" },
  { route: "catalog/bank/edit", moduleFile: "app/catalog/bank/bankEdit.ts", titleKey: "bank.titleOne" },
  { route: "catalog/bank/picker", moduleFile: "app/catalog/bank/bankPicker.ts", titleKey: "bank.titleMany" },
  { route: "catalog/chart_of_account/list", moduleFile: "app/catalog/chart_of_account/chartOfAccountList.ts", titleKey: "chartOfAccount.titleMany" },
  { route: "catalog/chart_of_account/edit", moduleFile: "app/catalog/chart_of_account/chartOfAccountEdit.ts", titleKey: "chartOfAccount.titleOne" },
  { route: "catalog/chart_of_account/picker", moduleFile: "app/catalog/chart_of_account/chartOfAccountPicker.ts", titleKey: "chartOfAccount.titleMany" },
  { route: "catalog/counterparty/list", moduleFile: "app/catalog/counterparty/counterpartyList.ts", titleKey: "counterparty.titleMany" },
  { route: "catalog/counterparty/edit", moduleFile: "app/catalog/counterparty/counterpartyEdit.ts", titleKey: "counterparty.titleOne" },
  { route: "catalog/counterparty/picker", moduleFile: "app/catalog/counterparty/counterpartyPicker.ts", titleKey: "counterparty.titleMany" },
  { route: "catalog/currency/list", moduleFile: "app/catalog/currency/currencyList.ts", titleKey: "currency.titleMany" },
  { route: "catalog/currency/edit", moduleFile: "app/catalog/currency/currencyEdit.ts", titleKey: "currency.titleOne" },
  { route: "catalog/currency/picker", moduleFile: "app/catalog/currency/currencyPicker.ts", titleKey: "currency.titleMany" },
  { route: "report/document_movements/list", moduleFile: "app/report/document_movements/documentMovementsReport.ts", titleKey: "documentMovements.title" },
  { route: "document/invoice/list", moduleFile: "app/document/invoice/invoiceList.ts", titleKey: "invoice.titleMany" },
  { route: "document/invoice/edit", moduleFile: "app/document/invoice/invoiceEdit.ts", titleKey: "invoice.titleOne" },
  { route: "operation/manual_entry/list", moduleFile: "app/operation/manual_entry/manualEntryList.ts", titleKey: "manualEntry.titleMany" },
  { route: "operation/manual_entry/edit", moduleFile: "app/operation/manual_entry/manualEntryEdit.ts", titleKey: "manualEntry.titleOne" },
  { route: "admin/menu/list", moduleFile: "app/admin/menu/menuList.ts", titleKey: "menu.titleMany" },
  { route: "admin/menu/edit", moduleFile: "app/admin/menu/menuEdit.ts", titleKey: "menu.titleOne" },
  { route: "catalog/nomenclature/list", moduleFile: "app/catalog/nomenclature/nomenclatureList.ts", titleKey: "nomenclature.titleMany" },
  { route: "catalog/nomenclature/edit", moduleFile: "app/catalog/nomenclature/nomenclatureEdit.ts", titleKey: "nomenclature.titleOne" },
  { route: "catalog/nomenclature/picker", moduleFile: "app/catalog/nomenclature/nomenclaturePicker.ts", titleKey: "nomenclature.titleMany" },
  { route: "admin/numerator/list", moduleFile: "app/admin/numerator/numeratorList.ts", titleKey: "numerator.titleMany" },
  { route: "admin/numerator/edit", moduleFile: "app/admin/numerator/numeratorEdit.ts", titleKey: "numerator.titleOne" },
  { route: "catalog/organization/list", moduleFile: "app/catalog/organization/organizationList.ts", titleKey: "organization.titleMany" },
  { route: "catalog/organization/edit", moduleFile: "app/catalog/organization/organizationEdit.ts", titleKey: "organization.titleOne" },
  { route: "catalog/organization/picker", moduleFile: "app/catalog/organization/organizationPicker.ts", titleKey: "organization.titleMany" },
  { route: "admin/print_template/list", moduleFile: "app/admin/print_template/printTemplateList.ts", titleKey: "printTemplate.titleMany" },
  { route: "admin/print_template/edit", moduleFile: "app/admin/print_template/printTemplateEdit.ts", titleKey: "printTemplate.titleOne" },
  { route: "report/turnover_balance/list", moduleFile: "app/report/turnover_balance/turnoverBalanceReport.ts", titleKey: "turnoverBalance.title" },
  { route: "admin/user/list", moduleFile: "app/admin/user/userList.ts", titleKey: "user.titleMany" },
  { route: "admin/user/edit", moduleFile: "app/admin/user/userEdit.ts", titleKey: "user.titleOne" },
  { route: "admin/user/picker", moduleFile: "app/admin/user/userPicker.ts", titleKey: "user.titleMany" },
  { route: "admin/user_group/list", moduleFile: "app/admin/user_group/userGroupList.ts", titleKey: "userGroup.titleMany" },
  { route: "admin/user_group/edit", moduleFile: "app/admin/user_group/userGroupEdit.ts", titleKey: "userGroup.titleOne" }
];

