-- Документ «Операція» — ручне введення проводок.
--
-- Власних реквізитів у шапки немає: усе, що потрібно, вже є в app.document.
-- Рядок у цій таблиці існує лише як точка кріплення табличної частини.
create table if not exists app.manual_entry (
  document_id bigint primary key references app.document (id) on delete cascade
);

-- Рядок проводки, як його ввів користувач.
--
-- Субконто зберігаються як jsonb {dimension_code: value_id} — це НАМІР
-- документа, а не рух. Нормалізовані рядки зі знімками представлень живуть у
-- app.journal_entry_analytic і з'являються при проведенні. Тому перейменування
-- в довіднику не чіпає документ, а історію у звітах не переписує.
create table if not exists app.manual_entry_line (
  id                bigint generated by default as identity primary key,
  document_id       bigint not null references app.manual_entry (document_id) on delete cascade,
  line_no           int    not null default 0,
  debit_account     varchar(10) references app.chart_of_account (code),
  credit_account    varchar(10) references app.chart_of_account (code),
  amount            numeric(18,2) not null default 0,
  quantity          numeric(18,3),
  debit_analytics   jsonb not null default '{}'::jsonb,
  credit_analytics  jsonb not null default '{}'::jsonb,
  description       text
);

create index if not exists ix_manual_entry_line_document on app.manual_entry_line (document_id);
