-- Підсистема доступу: користувачі, сесії, групи, права.
--
-- Живе у фреймворку, бо без неї не працює жоден застосунок: на app.users
-- посилаються app.document (created_by/updated_by/posted_by) і app.attachment
-- (created_by), а app.auth_session — основа авторизації.
--
-- Право описується трійкою «група → модель → дія». Модель — це ім'я з
-- manifest.json, тобто те саме, що приходить у ModelRuntimeService.execute():
-- завдяки цьому перевірка права лягає рівно на точку виконання команди.
--
-- Інтерфейсної частини тут немає навмисно. Фреймворк дає структури й функції;
-- екрани керування користувачами застосунок робить як і де йому зручно.

create extension if not exists pgcrypto;
create schema if not exists app;

-- Прив'язку доступу до «інтерфейсів» (наборів екранів) знято: право тепер
-- описується дією над моделлю, а не набором меню. Таблиці лишалися від
-- попереднього прототипу — їх не створював жоден чинний скрипт.
drop table if exists app.user_group_interface cascade;
drop table if exists app.user_interface cascade;

create table if not exists app.users (
  id            bigint generated by default as identity primary key,
  login         varchar(100) not null unique,
  -- Хеш рахує TS (PBKDF2-SHA256, див. server/modules/auth/password-hash.ts).
  -- SQL паролів не торкається свідомо: одна схема хешування, одне місце.
  password_hash varchar(255) not null,
  full_name     varchar(255) not null,
  is_active     boolean not null default true,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index if not exists ix_users_is_active on app.users (is_active);

create table if not exists app.auth_session (
  id           uuid primary key default gen_random_uuid(),
  user_id      bigint not null references app.users (id) on delete cascade,
  auth_method  varchar(50) not null,
  token_hash   varchar(64) not null unique,
  expires_at   timestamptz not null,
  last_seen_at timestamptz,
  revoked_at   timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index if not exists ix_auth_session_user_id on app.auth_session (user_id);
create index if not exists ix_auth_session_active_lookup on app.auth_session (token_hash, expires_at)
  where revoked_at is null;

-- Зв'язка користувача із зовнішнім провайдером входу.
--
-- Ключ — стабільний ідентифікатор у провайдера (OIDC `sub`), а не e-mail:
-- e-mail міняють, і зв'язка тихо переїхала б на іншу людину. Без рядка тут
-- зовнішній вхід не пускає нікого — навіть якщо провайдер підтвердив особу.
-- Виняток один: порожня база, коли зовнішнім входом заводиться перший
-- адміністратор (див. AuthIdentityService).
create table if not exists app.user_identity (
  id          bigint generated by default as identity primary key,
  user_id     bigint not null references app.users (id) on delete cascade,
  -- Ключ методу входу (`AuthMethod.key`), не назва компанії.
  provider    varchar(50) not null,
  external_id varchar(255) not null,
  -- Що провайдер сказав про особу на момент зв'язки. Довідково: жодне рішення
  -- на цих полях не будується, звіряння йде тільки по external_id.
  email       varchar(255),
  display_name varchar(255),
  last_login_at timestamptz,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- Одна зовнішня особа — не більше ніж один користувач.
create unique index if not exists uq_user_identity on app.user_identity (provider, external_id);
create index if not exists ix_user_identity_user on app.user_identity (user_id);

-- Разовий `state` redirect-потоку: захист від CSRF на callback.
--
-- У БД, а не в пам'яті процесу: `dev:server` ходить із --watch, і стан у пам'яті
-- помирав би при кожному перезапуску рівно посеред відлагодження редиректу.
-- Значення зберігається як є — за RFC 6749 `state` не секрет, а разовий nonce;
-- сам собою він нічого не відкриває, бо без `code` від провайдера сесії не буде.
create table if not exists app.auth_login_state (
  state       varchar(64) primary key,
  auth_method varchar(50) not null,
  -- Куди повернути користувача в інтерфейсі. Тільки шлях від кореня —
  -- абсолютний URL тут став би відкритим редиректом (перевіряє TS).
  redirect_to varchar(500),
  expires_at  timestamptz not null,
  -- Погашено: другий callback із тим самим state нічого не дасть.
  consumed_at timestamptz,
  created_at  timestamptz not null default now()
);

create index if not exists ix_auth_login_state_expires on app.auth_login_state (expires_at);

create table if not exists app.user_group (
  id         bigint generated by default as identity primary key,
  code       varchar(50) not null unique,
  name       varchar(255) not null,
  is_active  boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ix_user_group_is_active on app.user_group (is_active);

create table if not exists app.user_group_member (
  id            bigint generated by default as identity primary key,
  user_group_id bigint not null references app.user_group (id) on delete cascade,
  user_id       bigint not null references app.users (id) on delete cascade,
  is_active     boolean not null default true,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- Унікальність потрібна не лише для чистоти: на неї спирається ON CONFLICT
-- в AuthService.ensureDefaultAccess().
create unique index if not exists uq_user_group_member on app.user_group_member (user_group_id, user_id);
create index if not exists ix_user_group_member_user on app.user_group_member (user_id) where is_active;

-- Дії. Перші чотири мають сенс для будь-якої моделі, останні дві — лише для
-- документів (тип моделі оголошений у manifest.json, а не в БД, тому обмежити
-- їх на рівні таблиці не можна — це перевіряє рантайм).
--   view   — перегляд: list, get, lookup
--   create — введення нового запису
--   edit   — зміна наявного
--   delete — видалення
--   post   — проведення документа
--   unpost — скасування проведення
create table if not exists app.user_group_permission (
  id            bigint generated by default as identity primary key,
  user_group_id bigint not null references app.user_group (id) on delete cascade,
  -- Ім'я моделі з manifest.json або '*' — «усі моделі».
  model         varchar(100) not null,
  action        varchar(20) not null,
  is_allowed    boolean not null default true,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  constraint ck_user_group_permission_action
    check (action in ('view', 'create', 'edit', 'delete', 'post', 'unpost')),
  constraint ck_user_group_permission_model
    check (model = '*' or model ~ '^[a-z][a-z0-9_]*$')
);

create unique index if not exists uq_user_group_permission
  on app.user_group_permission (user_group_id, model, action);
create index if not exists ix_user_group_permission_group
  on app.user_group_permission (user_group_id) where is_allowed;
