create table if not exists app.counterparty (
  id         bigint generated by default as identity primary key,
  code       varchar(20)  not null,
  name       varchar(200) not null,
  is_active  boolean      not null default true,
  created_at timestamptz  not null default now(),
  updated_at timestamptz  not null default now()
);

create unique index if not exists uq_counterparty_code on app.counterparty (code);
create index if not exists ix_counterparty_name on app.counterparty (name);
